package it.polimi.ingsw.network.socket.server;

import it.polimi.ingsw.controller.GameController;
import it.polimi.ingsw.controller.ServerSideMessageListener;
import it.polimi.ingsw.network.messages.ClientToServerMessage;
import it.polimi.ingsw.network.messages.Message;
import it.polimi.ingsw.network.commonData.ConstantValues;
import it.polimi.ingsw.network.messages.ServerToClientMessage;


import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.concurrent.ArrayBlockingQueue;

import static it.polimi.ingsw.network.commonData.ConstantValues.maxMessagesInQueue;

public class ClientHandler extends Thread {

    /**
     * Debugging
     */
    String className = ClientHandler.class.getName();
    private boolean isPlaying=false;

    /**
     * ServerSideMessageListener of the related game
     */
    private ServerSideMessageListener gameController;

    /**
     * ObjectInputStream in
     */
    private ObjectInputStream in;

    /**
     * ObjectOutputStream out
     */
    private ObjectOutputStream out;

    /**
     * AudiencesHandlerServerSide of the related Game
     */
    //private AudiencesHandlerServerSide audiencesHandlerServerSide;

    /**
     * Client Socket, unchangeable
     */
    private final Socket clientSocket;

    /**
     * Creare a queue for messages that can take up to maxMessagesInQueue messages.
     * NB: not more than maxMessagesInQueue in order to limit the spam ability of clients
     */
    private ArrayBlockingQueue queue = new ArrayBlockingQueue(maxMessagesInQueue);

    /**
     * Used to handle Client needs
     *
     * @param clientSocket
     * @throws IOException
     */
    public ClientHandler(Socket clientSocket) throws IOException {
        this.clientSocket = clientSocket;
        this.in = new ObjectInputStream(clientSocket.getInputStream());
        this.out = new ObjectOutputStream(clientSocket.getOutputStream());
       // AudiencesHandlerServerSide audiencesHandlerServerSide = new AudiencesHandlerServerSide();
    }

    /**
     * Manages messages by client to server
     */
    public void run(){
        Thread tmp_thread = new Thread(this::executeMessage);
        tmp_thread.start();
/*
        try{
            Message message;
            while(!this.isInterrupted()){
                addMessageToQueue();
            }
        } catch(IOException | ClassNotFoundException e){
            System.out.print("\n\n!!! Error !!! (" + className + new Exception().getStackTrace()[0].getLineNumber() + ") Failed for some reasons!\n\n");
        } catch(IllegalStateException){
            System.out.print("\n\n!!! Error !!! (" + className + new Exception().getStackTrace()[0].getLineNumber() + ") Client is spamming messages!\n\n");
        }finally{
            tmp_thread.interrupt();
        }*/
    }

    public void executeMessage(){
        //try{
            ClientToServerMessage message;
            while(!this.isInterrupted()){
              //  message = queue.take();

                //
                // HOW TO CALL GAMECONTROLLER WITH A GENERIC MESSAGE !?!?!
                //

            }
      //  }
    }

    /**
     * Add a message to queue of messages
     */
    private void addMessageToQueue(){
        //message = (Message) in.readObject();
      // queue.add(message);
    }

    /**
     * Interrupt the thread
     */
    public void interruptSelf(){
        this.interrupt();
    }

    /**
     * Method used for debugging. It prints the number of elements that are inside the queue
     */
    private void printQueueNumberOfElements(){
        System.out.println("Elements in queue: " + queue.size());
    }

    /**
     * Flags the connection as one of the connections of the players of the game
     */
    public void setPlayerStatus(){
        isPlaying=true;
    }

    /**
     * If false this connection won't receive any message related to the game being played, only ones regarding the connection
     * @return true if the player has chosen a name false otherwise
     */
    public boolean isPlaying(){
        return isPlaying;
    }

    /**
     * Sends a message to the client
     * @param mes is the message generated by the controller
     * @throws IOException if there are problems sending the message
     */
    public void sendMessage(ServerToClientMessage mes) throws IOException {
        out.writeObject(mes);
    }
}