package it.polimi.ingsw.network.server;

import it.polimi.ingsw.network.messages.ServerToClientMessage;

import java.io.IOException;

/**
 * The ClientHandler class is an abstract class that defines the methods
 * required for handling client interactions in both socket and RMI implementations.
 * It extends the Thread class to allow concurrent processing of client messages.
 */
public abstract class ClientHandler extends Thread {

    /**
     * Receives messages from the client and processes them.
     */
    public abstract void receiveMessage();

    /**
     * Sends messages from the client to the server.
     */
    public abstract void passMessage();

    /**
     * Interrupts the current thread, stopping its execution.
     */
    public void interruptSelf() {
        this.interrupt();
    }

    /**
     * Sends a message to the client.
     *
     * @param mes the message generated by the controller.
     * @throws IOException if there is an error sending the message.
     */
    public abstract void sendMessage(ServerToClientMessage mes) throws IOException;

    /**
     * Notifies the client handler of a ping reception and sends a Pong as a response.
     */
    public abstract void pingWasReceived();

    /**
     * Periodically checks the connection status to ensure it is still active.
     * This method should handle timeouts and disconnections.
     */
    public abstract void checkConnectionStatus();

    /**
     * Ends the connection between the client and server, closing all necessary resources.
     */
    public abstract void stopConnection();
}