package it.polimi.ingsw.network.server;

import it.polimi.ingsw.network.messages.ServerToClientMessage;

import java.io.IOException;

/**
 * The ClientHandler class is an abstract class that defines the methods
 * required for handling client interactions
 * It extends the Thread class to allow concurrent processing of client messages.
 */
public interface ClientHandler{

    /**
     * Receives messages from the client and processes them.
     */
     void receiveMessage();

    /**
     * Sends messages from the client to the server.
     */
     void passMessage();
    /**
     * Sends a message to the client.
     *
     * @param mes the message generated by the controller.
     * @throws IOException if there is an error sending the message.
     */
     void sendMessage(ServerToClientMessage mes) throws IOException;

    /**
     * Notifies the client handler of a ping reception and sends a Pong as a response.
     */
     void pingWasReceived();

    /**
     * Periodically checks the connection status to ensure it is still active.
     */
     void checkConnectionStatus();

    /**
     * Ends the connection between the client and server, closing all necessary resources.
     */
     void stopConnection();
}