package it.polimi.ingsw.controller;

public enum ClientControllerState {
    CONNECTING,
    ENDING_CONNECTION,
    CHOOSING_NAME,
    CHOOSING_NUMBER_OF_PLAYERS,
    WAITING_FOR_START,
    CHOOSING_OBJECTIVE,
    CHOOSING_STARTING_CARD_FACE,
    REQUESTING_DRAW_CARD,
    REQUESTING_PLACEMENT,
    OTHER_PLAYER_TURN,
    GAME_SOFT_LOCKED,
    GAME_ENDING,

}
